import letterClass from 'utils/createLetterClass'

export let A = letterClass({ id: 0, name: 'A', freq: 'C3', glyph: require('glyphs/1-SQUAFO-ADSR-A.json') })
export let B = letterClass({ id: 1, name: 'B', freq: 'D3', glyph: require('glyphs/1-SQUAFO-ADSR-B.json') })
export let C = letterClass({ id: 2, name: 'C', freq: 'E3', glyph: require('glyphs/1-SQUAFO-ADSR-C.json') })
export let D = letterClass({ id: 3, name: 'D', freq: 'F3', glyph: require('glyphs/1-SQUAFO-ADSR-D.json') })
export let E = letterClass({ id: 4, name: 'E', freq: 'G3', glyph: require('glyphs/1-SQUAFO-ADSR-E.json') })
export let F = letterClass({ id: 5, name: 'F', freq: 'A3', glyph: require('glyphs/1-SQUAFO-ADSR-F.json') })
export let G = letterClass({ id: 6, name: 'G', freq: 'B3', glyph: require('glyphs/1-SQUAFO-ADSR-G.json') })
export let H = letterClass({ id: 7, name: 'H', freq: 'C4', glyph: require('glyphs/1-SQUAFO-ADSR-H.json') })
export let I = letterClass({ id: 8, name: 'I', freq: 'D4', glyph: require('glyphs/1-SQUAFO-ADSR-I.json') })
export let J = letterClass({ id: 9, name: 'J', freq: 'E4', glyph: require('glyphs/1-SQUAFO-ADSR-J.json') })
export let K = letterClass({ id: 10, name: 'K', freq: 'F4', glyph: require('glyphs/1-SQUAFO-ADSR-K.json') })
export let L = letterClass({ id: 11, name: 'L', freq: 'G4', glyph: require('glyphs/1-SQUAFO-ADSR-L.json') })
export let M = letterClass({ id: 12, name: 'M', freq: 'A4', glyph: require('glyphs/1-SQUAFO-ADSR-M.json') })
export let N = letterClass({ id: 13, name: 'N', freq: 'B4', glyph: require('glyphs/1-SQUAFO-ADSR-N.json') })
export let O = letterClass({ id: 14, name: 'O', freq: 'C5', glyph: require('glyphs/1-SQUAFO-ADSR-O.json') })
export let P = letterClass({ id: 15, name: 'P', freq: 'D5', glyph: require('glyphs/1-SQUAFO-ADSR-P.json') })
export let Q = letterClass({ id: 16, name: 'Q', freq: 'E5', glyph: require('glyphs/1-SQUAFO-ADSR-Q.json') })
export let R = letterClass({ id: 17, name: 'R', freq: 'F5', glyph: require('glyphs/1-SQUAFO-ADSR-R.json') })
export let S = letterClass({ id: 18, name: 'S', freq: 'G5', glyph: require('glyphs/1-SQUAFO-ADSR-S.json') })
export let T = letterClass({ id: 19, name: 'T', freq: 'A5', glyph: require('glyphs/1-SQUAFO-ADSR-T.json') })
export let U = letterClass({ id: 20, name: 'U', freq: 'B5', glyph: require('glyphs/1-SQUAFO-ADSR-U.json') })
export let V = letterClass({ id: 21, name: 'V', freq: 'C6', glyph: require('glyphs/1-SQUAFO-ADSR-V.json') })
export let W = letterClass({ id: 22, name: 'W', freq: 'D6', glyph: require('glyphs/1-SQUAFO-ADSR-W.json') })
export let X = letterClass({ id: 23, name: 'X', freq: 'E6', glyph: require('glyphs/1-SQUAFO-ADSR-X.json') })
export let Y = letterClass({ id: 24, name: 'Y', freq: 'F6', glyph: require('glyphs/1-SQUAFO-ADSR-Y.json') })
export let Z = letterClass({ id: 25, name: 'Z', freq: 'G6', glyph: require('glyphs/1-SQUAFO-ADSR-Z.json') })
