import letterClass from 'utils/createLetterClass'

export let A = letterClass({ id: 0, name: 'A', freq: 'C3', drawing: require('drawings/A') })
export let B = letterClass({ id: 1, name: 'B', freq: 'D3', drawing: require('drawings/B') })
export let C = letterClass({ id: 2, name: 'C', freq: 'E3', drawing: require('drawings/C') })
export let D = letterClass({ id: 3, name: 'D', freq: 'F3', drawing: require('drawings/D') })
export let E = letterClass({ id: 4, name: 'E', freq: 'G3', drawing: require('drawings/E') })
export let F = letterClass({ id: 5, name: 'F', freq: 'A3', drawing: require('drawings/F') })
export let G = letterClass({ id: 6, name: 'G', freq: 'B3', drawing: require('drawings/G') })
export let H = letterClass({ id: 7, name: 'H', freq: 'C4', drawing: require('drawings/H') })
export let I = letterClass({ id: 8, name: 'I', freq: 'D4', drawing: require('drawings/I') })
export let J = letterClass({ id: 9, name: 'J', freq: 'E4', drawing: require('drawings/J') })
export let K = letterClass({ id: 10, name: 'K', freq: 'F4', drawing: require('drawings/K') })
export let L = letterClass({ id: 11, name: 'L', freq: 'G4', drawing: require('drawings/L') })
// export let M = letterClass({ id: 12, name: 'M', freq: 'A4', drawing: require('drawings/M') })
// export let N = letterClass({ id: 13, name: 'N', freq: 'B4', drawing: require('drawings/N') })
export let O = letterClass({ id: 14, name: 'O', freq: 'C5', drawing: require('drawings/O') })
export let P = letterClass({ id: 15, name: 'P', freq: 'D5', drawing: require('drawings/P') })
export let Q = letterClass({ id: 16, name: 'Q', freq: 'E5', drawing: require('drawings/Q') })
export let R = letterClass({ id: 17, name: 'R', freq: 'F5', drawing: require('drawings/R') })
export let S = letterClass({ id: 18, name: 'S', freq: 'G5', drawing: require('drawings/S') })
export let T = letterClass({ id: 19, name: 'T', freq: 'A5', drawing: require('drawings/T') })
export let U = letterClass({ id: 20, name: 'U', freq: 'B5', drawing: require('drawings/U') })
export let V = letterClass({ id: 21, name: 'V', freq: 'C6', drawing: require('drawings/V') })
// export let W = letterClass({ id: 22, name: 'W', freq: 'D6', drawing: require('drawings/W') })
export let X = letterClass({ id: 23, name: 'X', freq: 'E6', drawing: require('drawings/X') })
// export let Y = letterClass({ id: 24, name: 'Y', freq: 'F6', drawing: require('drawings/Y') })
export let Z = letterClass({ id: 25, name: 'Z', freq: 'G6', drawing: require('drawings/Z') })
